### numpy array ops

In [2]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("basic slicing",arr[2:7])
print("with step",arr[1:8:2])
print("negative indexing", arr[-3])

basic slicing [3 4 5 6 7]
with step [2 4 6 8]
negative indexing 8


In [ ]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("shape: ",arr_2d.shape)
print("specific element", arr_2d[1,2])
print("entire row: ", arr_2d[2])
print("entire column: ", arr_2d[:,2]) # : is used for targetting all the rows

shape:  (3, 3)
specific element 6
entire row:  [7 8 9]
entire column:  [3 6 9]


## sorting

In [15]:
unsorted = np.array([3,2,1,6,1,2])
print("sorted array \n", np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print("sorted 2d array by column\n",np.sort(arr_2d_unsorted,axis=0))
print("sorted 2d array by row\n",np.sort(arr_2d_unsorted,axis=1))

sorted array 
 [1 1 2 2 3 6]
sorted 2d array by column
 [[1 1]
 [2 2]
 [3 3]]
sorted 2d array by row
 [[1 3]
 [1 2]
 [2 3]]


## filter

In [16]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0]
print("even numbers", even_number)

even numbers [ 2  4  6  8 10]


## filter with mask

In [ ]:
# mask basically stores an expression for evaluation
mask = numbers > 5
# and here its passed on to the numbers[]
print("numbers greater than 5 ",numbers[mask])
# returns boolean values for the elements that satify the expression
print(mask)

numbers greater than 5  [ 6  7  8  9 10]
[False False False False False  True  True  True  True  True]


## fancy indexing vs np.where()

In [ ]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers>5)
# it stores the indexes of the result
print(where_result)
print("np where",numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
np where [ 6  7  8  9 10]


In [ ]:
# similar to an if-else block
condition_array = np.where(numbers>5,"true","false")
print(condition_array)

(array([5, 6, 7, 8, 9]),)


## adding and removing data

In [23]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

# this gives matrix addition instead of merging the arrays
combined = arr1 + arr2
print(combined)

# to merge arrays u need to concat them by passing them as a tuple
combined_1 = np.concatenate((arr1,arr2))
print(combined_1)

[5 7 9]
[1 2 3 4 5 6]


## array compatibility

In [24]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("compatability shapes", a.shape == b.shape)

compatability shapes True


In [29]:
original = np.array([[1,2],[3,4]])

new_row = np.array([[5,6]])
with_new_row = np.vstack((original,new_row))
print("original\n",original)
print("with new row\n",with_new_row)

new_column = np.array([[7],[8]])
with_new_column = np.hstack((original,new_column))
print("original\n",original)
print("with new column\n",with_new_column)

original
 [[1 2]
 [3 4]]
with new row
 [[1 2]
 [3 4]
 [5 6]]
original
 [[1 2]
 [3 4]]
with new column
 [[1 2 7]
 [3 4 8]]


In [31]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print("array after deletion ",deleted)

array after deletion  [1 2 4 5]
