## Numpy array and basics

In [1]:
import numpy as np

creating arrays using list

In [2]:
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)

[1 2 3 4 5]


In [6]:
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


## diff between list and numpy

In [9]:
py_list = [1,2,3]
print("python list multiplication ", py_list*2)

python list multiplication  [1, 2, 3, 1, 2, 3]


In [ ]:
py_arr_1 =np.array([1,2,3]) #element wise multiplication
print("python array multiplication ", py_arr_1*2)

python array multiplication  [2 4 6]


In [ ]:
import time
start = time.time()
py_list_1 = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

#arange is just like the range ()- it consists of start,stop and step indexes
start = time.time()
np_arr = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)


 List operation time:  0.05851268768310547

 Numpy operation time:  0.005520343780517578


## creating array from scratch

In [ ]:
zeros = np.zeros((3,4))
print("zeros array: \n",zeros)

ones = np.ones((2,3))
print("ones array: \n",ones)

#square matrix with a constant value
full = np.full((2,2),4)
print("full array/square matrix: \n",full)

# random matrix
random = np.random.random((2,3))
print("random array/matrix: \n",random)

#sequence
sequence = np.arange(0,10,2)
print("sequence array: \n",sequence)


zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array/square matrix: 
 [[4 4]
 [4 4]]
random array/matrix: 
 [[0.47635227 0.03067852 0.69586675]
 [0.36604576 0.07503941 0.46603042]]
sequence array: 
 [0 1 2 3 4 5 6 7 8 9]


## vector,matrix and tensor

In [ ]:
# 1d arrays are vectors
vector = np.array([1,2,3])
print("vector: ",vector)

#2d arrays are known as matrix
matrix = np.array([[1,2,3],[4,5,6]])
print("matrix: \n",matrix)

#apart from 2d arrays everything else is a tensor
tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("tensor: \n",tensor)


vector:  [1 2 3]
matrix: 
 [[1 2 3]
 [4 5 6]]
tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## array properties

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print("shape ", arr.shape) # no of rows and columns 
print("dimension ",arr.ndim) # no of dimensions 1d,2d, etc
print("size ",arr.size) # total number of elements in the array
print("dtype ",arr.dtype) #data type of elements

shape  (2, 3)
dimension  2
size  6
dtype  int64


## array reshaping

In [36]:
arr = np.arange(12) #by default start is zero and step is one
print("original array: \n",arr)

# converting the original array into an array of (3,4) i.e. 3 rows and 4 columns
reshaped = arr.reshape((3,4)) 
print("reshaped array: \n",reshaped)

# flattens the reshaped array into a single row and flattens return copy
flattened = reshaped.flatten()
print("flattened array: \n", flattened)

# ravel(returns view(original),instead of copy)
raveled = reshaped.ravel()
print("raveled array: \n",raveled)

# transpose
transpose = reshaped.T
print("transposed array: \n",transpose)

original array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
transposed array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
